global:
  scrape_interval: 15s # Intervalo de coleta de métricas

scrape_configs:
  - job_name: 'stock-management-api'
    static_configs:
      - targets: ['host.docker.internal:3000'] # Endpoint da sua API NestJS
